apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/component: primary
    app.kubernetes.io/version: "v10.3.13"
generatorOptions:
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/component: primary
    app.kubernetes.io/version: "v10.3.13"
# secretGenerator:
#   - name: java
#     envs:
#     - secret/java.env
# configMapGenerator:
#   - name: api
#     envs:
#     - conf/api.env
resources:
  - statefulset.yaml
  - service.yaml
  - service-headless.yaml
  - secrets.yaml