apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/version: "v1.0.1"
generatorOptions:
  labels:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/version: "v1.0.1"
# secretGenerator:
#   - name: java
#     envs:
#     - secret/java.env
# configMapGenerator:
#   - name: api
#     envs:
#     - conf/api.env
resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - ingress.yaml